# -*- coding: utf-8 -*-
"""eda-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iM1LRlnYBvdrSnNPDgzuCb9-cRNC_72u
"""

# Downloaded the cutomer store csv
import kagglehub

# Download latest version
path = kagglehub.dataset_download("datascientistanna/customers-dataset")

print("Path to dataset files:", path)

import pandas as pd

df = pd.read_csv(
    "/root/.cache/kagglehub/datasets/datascientistanna/customers-dataset/versions/1/Customers.csv"
)

df.head()

# gives last rows
df.tail()

df.shape # method to check data rows and columns-rows:2000, columns:8

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Info:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

print("\nStatistics:")
display(df.describe())

# Catagorical view
print(df["Gender"].value_counts())

# Percentage
print(
    df["Gender"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

# Visualize
import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(
    data=df,
    x="Gender"
)

plt.title("Customer Distribution by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Customers")
plt.show()

# Neumerical data
print(df["Age"].describe())

# Histogram
sns.histplot(
    data=df,
    x="Age",
    bins=20,
    kde=True
)

plt.title("Age Distribution")
plt.show()

# Box plot
sns.boxplot(
    data=df,
    x="Age"
)

plt.title("Age Boxplot")
plt.show()

# Annual Income analysis
sns.histplot(
    data=df,
    x="Annual Income ($)",
    bins=20,
    kde=True
)

plt.title("Annual Income Distribution")
plt.show()

# Box plot
sns.boxplot(
    data=df,
    x="Annual Income ($)"
)

plt.title("Annual Income Boxplot")
plt.show()

# Spending Score analysis
sns.histplot(
    data=df,
    x="Spending Score (1-100)",
    bins=20,
    kde=True
)

plt.title("Spending Score Distribution")
plt.show()

# Boxplot
sns.boxplot(
    data=df,
    x="Spending Score (1-100)"
)

plt.title("Spending Score Boxplot")
plt.show()

# Detect outliers using IQR
def detect_outliers_iqr(data, column):

    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower_bound) |
        (data[column] > upper_bound)
    ]

    print("Column:", column)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower bound:", lower_bound)
    print("Upper bound:", upper_bound)
    print("Outliers:", len(outliers))

    return outliers

print("Age IQR\n")
age_outliers = detect_outliers_iqr(df, "Age")
print("\nIncome IQR\n")
income_outliers = detect_outliers_iqr(
    df,
    "Annual Income ($)"
)

# Bivariate EDA
sns.scatterplot(
    data=df,
    x="Age",
    y="Spending Score (1-100)"
)

plt.title("Age vs Spending Score")
plt.show()

# Income vs Spending
sns.scatterplot(
    data=df,
    x="Annual Income ($)",
    y="Spending Score (1-100)",
    hue="Gender"
)

plt.title("Annual Income vs Spending Score")
plt.show()

# Gender vs Spending
sns.boxplot(
    data=df,
    x="Gender",
    y="Spending Score (1-100)"
)

plt.title("Spending Score by Gender")
plt.show()
# Neumerically
df.groupby("Gender")[
    "Spending Score (1-100)"
].agg(["count", "mean", "median", "std"])

# Gender vs Income
sns.boxplot(
    data=df,
    x="Gender",
    y="Annual Income ($)"
)

plt.title("Annual Income by Gender")
plt.show()

# Correlation analysis
numeric_df = df.select_dtypes(include="number")

correlation = numeric_df.corr()

print(correlation)

# Visually
plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f"
)

plt.title("Correlation Matrix")
plt.show()

# Pairplot
sns.pairplot(
    df,
    hue="Gender"
)

plt.show()

# Customer segmentation visualization
plt.figure(figsize=(10, 7))

sns.scatterplot(
    data=df,
    x="Annual Income ($)",
    y="Spending Score (1-100)",
    hue="Gender",
    s=100
)

plt.title("Customer Segmentation Space")
plt.show()

# Prepare for K-Means
X = df[
    [
        "Annual Income ($)",
        "Spending Score (1-100)"
    ]
]

# Visually
plt.figure(figsize=(10, 7))

plt.scatter(
    X["Annual Income ($)"],
    X["Spending Score (1-100)"]
)

plt.xlabel("Annual Income ($)")
plt.ylabel("Spending Score")
plt.title("Customer Data Before Clustering")

plt.show()

# EDA with standardized data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled[:5])

# Compare
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled[:5])

# PCA EDA
from sklearn.decomposition import PCA

pca = PCA(n_components=2)

X_pca = pca.fit_transform(X_scaled)

print(
    "Explained variance:",
    pca.explained_variance_ratio_
)

# Visually
plt.scatter(
    X_pca[:, 0],
    X_pca[:, 1]
)

plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("PCA Visualization")

plt.show()

!pip install ydata-profiling
# Automatically generate an EDA report
from ydata_profiling import ProfileReport

profile = ProfileReport(
    df,
    title="E-Commerce Customer EDA Report",
    explorative=True
)

profile.to_notebook_iframe()

# Save to html
profile.to_file(
    "ecommerce_eda_report.html"
)

# Build an EDA pipeline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# =========================
# 1. LOAD DATA
# =========================

df = pd.read_csv("/root/.cache/kagglehub/datasets/datascientistanna/customers-dataset/versions/1/Customers.csv")


# =========================
# 2. BASIC INFORMATION
# =========================

print("=" * 60)
print("DATASET SHAPE")
print("=" * 60)

print(df.shape)


print("\nCOLUMNS")
print(df.columns.tolist())


print("\nDATA TYPES")
print(df.dtypes)


print("\nINFO")
df.info()


# =========================
# 3. DUPLICATES
# =========================

print("\nDUPLICATES")
print(df.duplicated().sum())


# =========================
# 4. MISSING VALUES
# =========================

print("\nMISSING VALUES")

missing = pd.DataFrame({
    "count": df.isnull().sum(),
    "percentage": (
        df.isnull().sum() / len(df) * 100
    )
})

print(
    missing.sort_values(
        "percentage",
        ascending=False
    )
)


# =========================
# 5. STATISTICS
# =========================

print("\nNUMERICAL STATISTICS")

print(
    df.describe()
)


# =========================
# 6. CATEGORICAL STATISTICS
# =========================

print("\nCATEGORICAL STATISTICS")

print(
    df.describe(include="object")
)


# =========================
# 7. UNIQUE VALUES
# =========================

print("\nUNIQUE VALUES")

for col in df.columns:
    print(
        col,
        "→",
        df[col].nunique()
    )


# =========================
# 8. NUMERICAL FEATURES
# =========================

numeric_columns = df.select_dtypes(
    include=np.number
).columns

print("\nNUMERICAL FEATURES:")
print(list(numeric_columns))


# =========================
# 9. CATEGORICAL FEATURES
# =========================

categorical_columns = df.select_dtypes(
    include="object"
).columns

print("\nCATEGORICAL FEATURES:")
print(list(categorical_columns))


# =========================
# 10. DISTRIBUTIONS
# =========================

for column in numeric_columns:

    plt.figure(figsize=(8, 5))

    sns.histplot(
        data=df,
        x=column,
        kde=True
    )

    plt.title(
        f"Distribution of {column}"
    )

    plt.show()


# =========================
# 11. BOXPLOTS
# =========================

for column in numeric_columns:

    plt.figure(figsize=(8, 4))

    sns.boxplot(
        data=df,
        x=column
    )

    plt.title(
        f"Boxplot of {column}"
    )

    plt.show()


# =========================
# 12. CORRELATION
# =========================

plt.figure(figsize=(10, 7))

sns.heatmap(
    df[numeric_columns].corr(),
    annot=True,
    fmt=".2f"
)

plt.title("Correlation Matrix")

plt.show()